// Generated by CoffeeScript 1.6.3
(function() {
  window.app = window.app || {};

  window.app.FiltersView = Backbone.View.extend({
    tagName: 'div',
    paginationTemplate: _.template($('#pagination-template').html()),
    searchTemplate: _.template($('#search-template').html()),
    events: {
      'click #pagination-back-button': 'pageBack',
      'click #pagination-forward-button': 'pageForward'
    },
    initialize: function() {
      this.paginationContainerClassName = 'pagination-container';
      this.$filtersContainer = $('.filters');
    },
    render: function() {
      this.$el.addClass(this.paginationContainerClassName).html(this.paginationTemplate(window.app.friends.page));
      return this;
    },
    pageBack: function(e) {
      e.preventDefault();
      window.app.friends.page.currentPage--;
      return window.app.friends.trigger('pageUpdate');
    },
    pageForward: function(e) {
      e.preventDefault();
      window.app.friends.page.currentPage++;
      return window.app.friends.trigger('pageUpdate');
    }
  });

}).call(this);
