// Generated by CoffeeScript 1.6.3
(function() {
  window.app = window.app || {};

  window.app.PaginationView = Backbone.View.extend({
    tagName: 'div',
    className: 'pagination-container',
    template: _.template($('#pagination-template').html()),
    initialize: function() {},
    render: function() {
      return this;
    }
  });

}).call(this);
