// Generated by CoffeeScript 1.6.3
(function() {
  window.app = window.app || {};

  window.app.page = {
    sorting: {
      sortAttribute: 'name',
      sortDirection: 1
    },
    page_defaults: {
      page: 1,
      currentPage: 1,
      perPage: 10
    },
    reset: function() {
      return this.info.currentPage = 1;
    },
    updatePageInfo: function(collection) {
      var currentPage, finish, start, totalFriends, totalPages;
      totalFriends = collection.models.length;
      totalPages = Math.ceil(totalFriends / this.page_defaults.perPage);
      currentPage = this.info != null ? this.info.currentPage : this.page_defaults.currentPage;
      currentPage = totalFriends ? currentPage : 0;
      start = currentPage * 10 !== 10 ? (currentPage - 1) * 10 : 0;
      finish = currentPage * 10;
      return this.info = {
        totalFriends: totalFriends,
        totalPages: totalPages,
        currentPage: currentPage,
        start: start,
        finish: finish
      };
    }
  };

  window.app.page = _.extend(window.app.page, Backbone.Events);

}).call(this);
