// Generated by CoffeeScript 1.6.3
(function() {
  window.app = window.app || {};

  window.app.Friends = Backbone.Collection.extend({
    model: window.app.Friend,
    url: '/me?fields=picture,friends.fields(id,name,gender,devices,picture)',
    sortAttribute: 'name',
    sortDirection: 1,
    comparator: function(a, b) {
      a = a.get(this.sortAttribute);
      b = b.get(this.sortAttribute);
      if (a === b) {
        return 0;
      }
      if (this.sortDirection === 1) {
        if (a > b) {
          return 1;
        } else {
          return -1;
        }
      } else {
        if (a < b) {
          return 1;
        } else {
          return -1;
        }
      }
    },
    sortFriends: function(attribute) {
      this.sortAttribute = attribute;
      return this.sort();
    },
    search: function(searchText) {
      var filtered, pattern;
      pattern = new RegExp(searchText, 'i');
      filtered = this.filter(function(friend) {
        return pattern.test(friend.get('name'));
      });
      return new window.app.Friends(filtered);
    },
    sync: function(method, model, options) {
      return window.FB.api(model.url, function(response) {
        if (!response || response.error) {
          options.error(response);
          return;
        }
        console.log('___FACEBOOK GRAPH DATA___');
        console.log(response);
        options.facebookResponse = response;
        options.success(response.friends.data, response, options);
      });
    }
  });

  window.app.friends = new window.app.Friends();

}).call(this);
