// Generated by CoffeeScript 1.6.3
(function() {
  var logToConsole, object;

  logToConsole = function(msg) {
    console.log('Triggered ' + msg);
    console.log(this);
  };

  object = {};

  _.extend(object, Backbone.Events);

  object.on('console:log', logToConsole);

  object.trigger('console:log', 'a log event');

  object.off();

  object.trigger('console:log', 'a log event');

}).call(this);
